'use client';

import React, { useEffect, useState, useMemo } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  ShoppingCart, Check, Info, ShieldCheck, Truck,
  RotateCcw, Star, Minus, Plus, Loader2,
  ChevronRight, Bookmark, Share2, Tag, CreditCard, X
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import { api } from '@/lib/api';
import { Product, Plan } from '@/types';
import { useCartStore } from '@/store/cartStore';
import { useToast } from '@/components/ui/Toast';
import { cn } from '@/lib/utils';
import { useAuth } from '@/app/context/AuthContext';

export default function ProductDetailPage() {
  const { productId } = useParams();
  const router = useRouter();
  const { user } = useAuth();
  const { success: toastSuccess, error: toastError } = useToast();
  const addItem = useCartStore(s => s.addItem);

  const [product, setProduct] = useState<Product | null>(null);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedPlanId, setSelectedPlanId] = useState<string | null>(null);
  const [selectedVariantId, setSelectedVariantId] = useState<string | null>(null);
  const [quantity, setQuantity] = useState(1);
  const [selectedImage, setSelectedImage] = useState(0);
  const [isCheckoutOpen, setIsCheckoutOpen] = useState(false);
  const [isPaying, setIsPaying] = useState(false);

  useEffect(() => {
    async function fetchData() {
      try {
        const [prodRes, plansRes] = await Promise.all([
          api.products.getById(productId as string),
          api.plans.getAll({ productId })
        ]);

        if (prodRes.success) {
          setProduct(prodRes.data);
          if (prodRes.data.variants && prodRes.data.variants.length > 0) {
            setSelectedVariantId(prodRes.data.variants[0].id || prodRes.data.variants[0]._id as string);
          }
        }
        if (plansRes.success) {
          const plansData = plansRes.data as any;
          const normalizedPlans = Array.isArray(plansData) ? plansData : (plansData?.plans ?? []);
          setPlans(normalizedPlans);
          if (normalizedPlans.length > 0) {
            setSelectedPlanId(normalizedPlans[0].id || normalizedPlans[0]._id);
          }
        }
      } catch (err) {
        console.error('Failed to fetch product data', err);
        toastError('Error', 'Product not found or failed to load.');
      } finally {
        setIsLoading(false);
      }
    }
    fetchData();
  }, [productId]);

  const selectedPlan = useMemo(() =>
    plans.find((p: any) => (p.id || p._id) === selectedPlanId),
    [plans, selectedPlanId]);

  const getProductId = (p: Product) => p.id || p._id || '';

  const selectedVariant = useMemo(() =>
    product?.variants?.find(v => (v.id || v._id) === selectedVariantId),
    [product, selectedVariantId]);

  const totalPricePerUnit = useMemo(() => {
    const base = selectedPlan?.price ?? product?.basePrice ?? 0;
    const extra = selectedVariant?.extraPrice || 0;
    return base + extra;
  }, [selectedPlan, selectedVariant, product]);

  const billingLabel = useMemo(() => {
    if (selectedPlan?.billingCycle) return selectedPlan.billingCycle;
    return product?.unitLabel || 'unit';
  }, [selectedPlan, product]);

  const handleAddToCart = () => {
    if (!product) return;
    const productId = getProductId(product);
    if (!productId) {
      toastError('Unable to add', 'This product is missing an identifier. Please refresh and try again.');
      return;
    }
    if (totalPricePerUnit <= 0) {
      toastError('Invalid amount', 'This product has no payable amount yet.');
      return;
    }

    const planId = (selectedPlan as any)?.id || (selectedPlan as any)?._id || `base-${productId}`;
    const planLabel = selectedPlan?.name || `${product.name} Base`;

    addItem({
      id: '', // Generated by store
      productId,
      name: product.name,
      planId,
      planLabel,
      variantId: selectedVariantId || undefined,
      variantLabel: selectedVariant ? `${selectedVariant.attribute}: ${selectedVariant.value}` : undefined,
      billingPeriod: billingLabel,
      price: totalPricePerUnit,
      quantity: quantity,
      image: ''
    });

    toastSuccess('Added to Cart', `${product.name} (${planLabel}) added successfully.`);
  };

  const handleRazorpayCheckout = () => {
    if (!product) return;
    if (typeof window === 'undefined' || !(window as any).Razorpay) {
      toastError('Razorpay unavailable', 'Payment SDK not loaded yet. Please try again in a moment.');
      return;
    }

    const razorpayKey = process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID;
    if (!razorpayKey) {
      toastError('Razorpay key missing', 'Set NEXT_PUBLIC_RAZORPAY_KEY_ID in frontend environment.');
      return;
    }

    setIsPaying(true);

    const totalAmount = totalPricePerUnit * quantity;
    const options = {
      key: razorpayKey,
      amount: Math.round(totalAmount * 100),
      currency: 'INR',
      name: 'Plano Subscriptions',
      description: `${product.name} (${quantity} x ${billingLabel})`,
      image: 'https://cdn.razorpay.com/logos/H6U6f9bA6G6E7M_medium.png',
      prefill: {
        name: user?.name,
        email: user?.email,
      },
      theme: { color: '#8f5580' },
      handler: (response: any) => {
        setIsPaying(false);
        setIsCheckoutOpen(false);
        toastSuccess('Payment Captured', `Transaction ID: ${response.razorpay_payment_id}`);
        router.push(`/portal/order/confirmation?id=${response.razorpay_payment_id}&ref=${response.razorpay_payment_id}`);
      },
      modal: {
        ondismiss: () => setIsPaying(false),
      },
    };

    const rzp = new (window as any).Razorpay(options);
    rzp.open();
  };

  function closeCheckoutModal() {
    if (isPaying) return;
    setIsCheckoutOpen(false);
  }

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="animate-spin text-plano-600" size={32} />
      </div>
    );
  }

  if (!product) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-6 text-center">
        <div className="w-20 h-20 rounded-full bg-danger-50 flex items-center justify-center text-danger-500 mb-6">
          <Info size={40} />
        </div>
        <h2 className="text-2xl font-bold text-plano-900 mb-4 uppercase">Product Not Found</h2>
        <Link href="/portal/shop" className="btn-primary">Back to Shop</Link>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-6 py-12">
      {/* Breadcrumb */}
      <nav className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-gray-400 mb-12">
        <Link href="/portal/shop" className="hover:text-plano-600 transition-colors">Shop</Link>
        <ChevronRight size={12} />
        <span className="text-gray-300">{product.type}</span>
        <ChevronRight size={12} />
        <span className="text-plano-900">{product.name}</span>
      </nav>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
        {/* Left: Visuals */}
        <div className="space-y-6">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="aspect-square rounded-[3rem] border border-plano-100 bg-white shadow-sm overflow-hidden flex items-center justify-center group relative"
          >
            {/* Mocking placeholder visuals */}
            <div className="absolute inset-0 bg-gradient-to-br from-plano-50 to-white flex items-center justify-center group-hover:scale-105 transition-transform duration-700">
              <Star size={120} className="text-plano-200" strokeWidth={0.5} />
            </div>
            <div className="absolute top-8 right-8 flex gap-2">
              <button className="w-10 h-10 rounded-full bg-white/90 backdrop-blur-md border border-plano-100 flex items-center justify-center text-gray-400 hover:text-plano-600 transition-all shadow-sm">
                <Bookmark size={18} />
              </button>
              <button className="w-10 h-10 rounded-full bg-white/90 backdrop-blur-md border border-plano-100 flex items-center justify-center text-gray-400 hover:text-plano-600 transition-all shadow-sm">
                <Share2 size={18} />
              </button>
            </div>
            {product.taxApplicable && (
              <div className="absolute top-8 left-8 h-8 px-4 rounded-full bg-success-50 text-success-700 border border-success-100 flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest shadow-sm">
                <ShieldCheck size={14} />
                Tax Included
              </div>
            )}
          </motion.div>

          <div className="grid grid-cols-4 gap-4">
            {[0, 1, 2, 3].map(i => (
              <button
                key={i}
                onClick={() => setSelectedImage(i)}
                className={cn(
                  "aspect-square rounded-2xl border transition-all overflow-hidden flex items-center justify-center bg-white",
                  selectedImage === i ? "border-plano-600 ring-4 ring-plano-600/5 shadow-md" : "border-plano-100 hover:border-plano-300"
                )}
              >
                <Star size={24} className={cn(selectedImage === i ? "text-plano-600" : "text-plano-100")} strokeWidth={1} />
              </button>
            ))}
          </div>
        </div>

        {/* Right: Actions & Info */}
        <div className="flex flex-col h-full">
          <div className="mb-8">
            <div className="flex items-center gap-2 mb-4">
              <div className="px-3 py-1 rounded-full bg-plano-50 border border-plano-100 text-plano-600 text-[10px] font-bold uppercase tracking-widest">
                {product.type}
              </div>
              <div className="flex items-center gap-1">
                {[1, 2, 3, 4, 5].map(i => <Star key={i} size={12} fill="#FBB130" stroke="#FBB130" />)}
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-plano-900 leading-tight mb-4 tracking-tight uppercase">{product.name}</h1>
            <p className="text-gray-500 font-medium text-lg leading-relaxed">{product.description}</p>
          </div>

          {/* Plan Selection */}
          <div className="mb-10">
            <h3 className="text-[11px] font-bold text-plano-600 uppercase tracking-widest mb-4 flex items-center gap-2">
              <Tag size={14} />
              Select Your Plan
            </h3>
            {plans.length > 0 ? (
              <div className="space-y-3">
                {plans.map((plan) => {
                  const isActive = selectedPlanId === plan.id;
                  return (
                    <button
                      key={plan.id}
                      onClick={() => setSelectedPlanId(plan.id)}
                      className={cn(
                        "w-full p-5 rounded-3xl border transition-all text-left flex items-center justify-between group",
                        isActive
                          ? "bg-white border-plano-600 ring-4 ring-plano-600/5 shadow-xl"
                          : "bg-white/50 border-plano-100 hover:border-plano-300 hover:bg-white"
                      )}
                    >
                      <div className="flex items-center gap-4">
                        <div className={cn(
                          "w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all",
                          isActive ? "border-plano-600 bg-plano-600" : "border-plano-100"
                        )}>
                          {isActive && <Check size={14} className="text-white" strokeWidth={3} />}
                        </div>
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="text-sm font-bold text-plano-900 uppercase tracking-tight">{plan.name}</span>
                            {plan.billingCycle === 'yearly' && (
                              <span className="px-2 py-0.5 rounded-lg bg-success-50 text-success-600 text-[10px] font-bold uppercase tracking-widest">Best Value</span>
                            )}
                          </div>
                          <p className="text-xs font-medium text-gray-400 mt-0.5">{plan.description || `Billed ${plan.billingCycle}`}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="text-xl font-bold text-plano-900">₹{plan.price.toLocaleString()}</div>
                        <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest italic">/ {plan.billingCycle}</span>
                      </div>
                    </button>
                  );
                })}
              </div>
            ) : (
              <div className="w-full p-5 rounded-3xl border bg-white border-plano-100 flex items-center justify-between">
                <div>
                  <span className="text-sm font-bold text-plano-900 uppercase tracking-tight">Base Product Pricing</span>
                  <p className="text-xs font-medium text-gray-400 mt-0.5">No plan variants configured for this product.</p>
                </div>
                <div className="text-right">
                  <div className="text-xl font-bold text-plano-900">₹{(product.basePrice || 0).toLocaleString()}</div>
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest italic">/ {product.unitLabel || 'unit'}</span>
                </div>
              </div>
            )}
          </div>

          {/* Variant Selection */}
          {product.variants && product.variants.length > 0 && (
            <div className="mb-10">
              <h3 className="text-[11px] font-bold text-plano-600 uppercase tracking-widest mb-4 flex items-center gap-2">
                <ShieldCheck size={14} />
                Select Package Type
              </h3>
              <div className="flex flex-wrap gap-3">
                {product.variants.map((variant) => {
                  const vId = variant.id || variant._id;
                  const isActive = selectedVariantId === vId;
                  return (
                    <button
                      key={vId}
                      onClick={() => setSelectedVariantId(vId as string)}
                      className={cn(
                        "px-6 py-3 rounded-2xl border transition-all text-sm font-bold uppercase tracking-widest flex items-center gap-3",
                        isActive
                          ? "bg-plano-600 border-plano-600 text-white shadow-xl shadow-plano-600/20"
                          : "bg-white border-plano-100 text-gray-400 hover:border-plano-300"
                      )}
                    >
                      <span>{variant.attribute}: {variant.value}</span>
                      {variant.extraPrice > 0 && (
                        <span className={cn(
                          "px-2 py-0.5 rounded-lg text-[10px]",
                          isActive ? "bg-white/20 text-white" : "bg-plano-50 text-plano-600"
                        )}>
                          +₹{variant.extraPrice}
                        </span>
                      )}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* Purchase Area */}
          <div className="mt-auto pt-8 border-t border-plano-50">
            <div className="flex items-center gap-6 mb-8">
              <div className="flex flex-col gap-1.5">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Quantity</span>
                <div className="h-14 px-4 bg-white border border-plano-100 rounded-2xl flex items-center gap-4 shadow-sm">
                  <button onClick={() => setQuantity(q => Math.max(1, q - 1))} className="text-gray-400 hover:text-plano-600 transition-colors"><Minus size={18} /></button>
                  <span className="w-8 text-center text-sm font-bold text-plano-900">{quantity}</span>
                  <button onClick={() => setQuantity(q => q + 1)} className="text-gray-400 hover:text-plano-600 transition-colors"><Plus size={18} /></button>
                </div>
              </div>
              <div className="flex-1">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest block mb-1.5">Total Price</span>
                <div className="h-14 flex items-center justify-between">
                  <h2 className="text-3xl font-bold text-plano-900 tabular-nums">
                    ₹{(totalPricePerUnit * quantity).toLocaleString()}
                  </h2>
                </div>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={handleAddToCart}
                className="flex-1 h-16 rounded-[2rem] bg-plano-600 text-white font-bold text-sm uppercase tracking-widest flex items-center justify-center gap-3 transition-all hover:bg-plano-900 hover:shadow-2xl hover:-translate-y-1 shadow-lg shadow-plano-600/20"
              >
                <ShoppingCart size={18} />
                Add to Cart
              </button>
              <button
                onClick={() => setIsCheckoutOpen(true)}
                className="h-16 px-6 flex-shrink-0 rounded-[2rem] border border-plano-100 bg-white text-plano-700 flex items-center justify-center gap-2 hover:border-plano-600 hover:text-plano-600 transition-all shadow-sm text-[10px] font-bold uppercase tracking-widest"
              >
                <CreditCard size={16} /> Pay Now
              </button>
            </div>

            {/* Guarantees */}
            <div className="mt-8 grid grid-cols-2 gap-4">
              <div className="flex items-center gap-2 text-[10px] font-bold text-gray-400 uppercase tracking-widest">
                <Truck size={14} className="text-plano-600" />
                Instant Activation
              </div>
              <div className="flex items-center gap-2 text-[10px] font-bold text-gray-400 uppercase tracking-widest">
                <RotateCcw size={14} className="text-plano-600" />
                30-Day Money Back
              </div>
            </div>
          </div>
        </div>
      </div>

      <AnimatePresence>
        {isCheckoutOpen && (
          <div className="fixed inset-0 z-[220] flex items-center justify-center p-6">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="absolute inset-0 bg-plano-900/60 backdrop-blur-md"
              onClick={closeCheckoutModal}
            />

            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              transition={{ duration: 0.2 }}
              className="bg-white rounded-[2.5rem] w-full max-w-xl overflow-hidden shadow-2xl relative z-10 border border-white/20"
            >
              <div className="bg-plano-900 p-7 text-white relative overflow-hidden">
                <div className="absolute top-0 right-0 w-28 h-28 bg-plano-600 opacity-20 blur-3xl rounded-full" />
                <div className="relative z-10 flex items-start justify-between gap-4">
                  <div>
                    <p className="text-[10px] font-bold uppercase tracking-widest text-plano-200">Razorpay Checkout</p>
                    <h2 className="text-2xl font-bold mt-2">{product.name}</h2>
                    <p className="text-xs text-white/70 mt-1 uppercase tracking-widest">{product.type}</p>
                  </div>
                  <button
                    disabled={isPaying}
                    onClick={closeCheckoutModal}
                    className="w-8 h-8 rounded-full border border-white/10 flex items-center justify-center hover:bg-white/10 transition-colors disabled:opacity-50"
                  >
                    <X size={14} />
                  </button>
                </div>
              </div>

              <div className="p-7">
                <p className="text-xs text-gray-500 font-medium leading-relaxed mb-6 uppercase tracking-tight">
                  {product.description || 'Secure online payment with Razorpay only for portal checkout.'}
                </p>

                <div className="rounded-2xl border border-plano-50 bg-plano-50/10 p-4 mb-6">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Unit Price</span>
                    <span className="text-sm font-bold text-plano-900">₹{totalPricePerUnit.toLocaleString()} / {billingLabel}</span>
                  </div>

                  <div className="flex items-center justify-between mb-3">
                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Quantity</span>
                    <div className="h-10 px-3 bg-white border border-plano-100 rounded-xl flex items-center gap-4">
                      <button disabled={isPaying} onClick={() => setQuantity((q) => Math.max(1, q - 1))} className="text-gray-400 hover:text-plano-900 disabled:opacity-50"><Minus size={14} /></button>
                      <span className="w-4 text-center text-xs font-bold text-plano-900">{quantity}</span>
                      <button disabled={isPaying} onClick={() => setQuantity((q) => q + 1)} className="text-gray-400 hover:text-plano-900 disabled:opacity-50"><Plus size={14} /></button>
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-plano-100">
                    <span className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Total Payable</span>
                    <span className="text-2xl font-bold text-plano-900 tabular-nums">₹{(totalPricePerUnit * quantity).toLocaleString()}</span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <button
                    onClick={handleAddToCart}
                    disabled={isPaying}
                    className="flex-1 h-14 rounded-2xl border border-plano-100 text-plano-600 text-[10px] font-bold uppercase tracking-widest hover:bg-plano-50 transition-all disabled:opacity-60"
                  >
                    Add to Cart
                  </button>
                  <button
                    onClick={handleRazorpayCheckout}
                    disabled={isPaying || totalPricePerUnit <= 0}
                    className="flex-[2] h-14 rounded-2xl bg-plano-900 text-white text-[10px] font-bold uppercase tracking-widest flex items-center justify-center gap-3 hover:bg-plano-600 transition-all shadow-xl shadow-plano-600/20 active:scale-95 px-6 group disabled:opacity-60 disabled:cursor-not-allowed"
                  >
                    {isPaying ? <Loader2 size={16} className="animate-spin" /> : <CreditCard size={16} />}
                    {isPaying ? 'Opening Razorpay...' : 'Pay With Razorpay'}
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
